player_death.register_stones('default:acacia_wood', 'acacia', 'Acacia', 'default_acacia_wood')
player_death.register_stones('default:aspen_wood', 'aspen', 'Aspen', 'default_aspen_wood')
player_death.register_stones('default:bronze_ingot', 'bronze', 'Bronze', 'default_bronze_block')
player_death.register_stones('default:clay', 'clay', 'Clay', 'default_clay')
player_death.register_stones('default:coalblock', 'coal', 'Coal', 'default_coal_block')
player_death.register_stones('default:cobble', 'cobble', 'Cobblestone', 'default_cobble')
player_death.register_stones('default:copper_ingot', 'copper', 'Copper', 'default_copper_block')
player_death.register_stones('default:coral_skeleton', 'coral', 'Coral', 'default_coral_skeleton')
player_death.register_stones('default:desert_sandstone', 'desert_sandstone', 'Desert Sandstone', 'default_desert_sandstone')
player_death.register_stones('default:desert_stone', 'desert_stone', 'Desert Stone', 'default_desert_stone')
player_death.register_stones('default:diamond', 'diamond', 'Diamond', 'default_diamond_block')
player_death.register_stones('default:gold_ingot', 'gold', 'Gold', 'default_gold_block')
player_death.register_stones('default:junglewood', 'junglewood', 'Junglewood', 'default_junglewood')
player_death.register_stones('default:mossycobble', 'mossycobble', 'Mossy Cobblestone', 'default_mossycobble')
player_death.register_stones('default:obsidian', 'obsidian', 'Obsidian', 'default_obsidian')
player_death.register_stones('default:pine_wood', 'pine', 'Pine', 'default_pine_wood')
player_death.register_stones('default:sandstone', 'sandstone', 'Sandstone', 'default_sandstone')
player_death.register_stones('default:silver_sandstone', 'silver_sandstone', 'Silver Sandstone', 'default_silver_sandstone')
player_death.register_stones('default:steel_ingot', 'steel', 'Steel', 'default_steel_block')
player_death.register_stones('default:stone', 'stone', 'Stone', 'default_stone')
player_death.register_stones('default:tin_ingot', 'tin', 'Tin', 'default_tin_block')
player_death.register_stones('default:wood', 'wood', 'Wood', 'default_wood')
